# deploy:
#   local_dir: public # Default static site output dir for Hugo
#   repo: CreatureSurvive/repo.github.io # This is the slug of the repo you want to deploy your site to
#   target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
#   email: support@creaturecoding.com
#   name: "CreatureSurvive"
#   on:
#     branch: master

language: go

env:
  global:
  - HUGO_VERSION=0.40.2  # set in the environment to make it easy 

# install hugo before the build is run; download the public
# release, untar, and copy it to a known location
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

# on build attempt to generate the site
script:
- hugo

# the deploy configuration for github pages; this is an
# out-of-the-box travis feature
deploy:
  provider: pages
  # publish the "public" folder, where hugo builds by default
  local_dir: public
  skip_cleanup: true
  # use the github token stored in the environment, which is
  # securely encrypted in `matrix.secure` above
  github_token: "$GITHUB_TOKEN"
  # only publish on master branch builds
  on:
    branch: master